version: '3.9'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - ${HOST_MACHINE_DB_DATA_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  backend:
    volumes:
      - static_volume:/app/static
      - ${HOST_MACHINE_LOGS_PATH}/backend:/app/logs
    env_file:
      - ./.env
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - frontend:/app/dist/

  nginx:
    image: nginx:1.24-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/backend_static/
      - frontend:/var/www/frontend
      - ${HOST_MACHINE_LOGS_PATH}/nginx:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  frontend: