version: '3.9'

services:
  backend:
    volumes:
      - static_volume:/app/static
    env_file:
      - backend/backend/.env
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine
    volumes:
      - ${DB_LOCAL_DATA_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/dist/

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/backend_static/
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  frontend: