version: '3.8'

services:
  backend:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application
    volumes:
      - ./app/:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Maudeg12.34
      - POSTGRES_DB=backend
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Maudeg12.34
      - POSTGRES_DB=backend

volumes:
  postgres_data:
  static_volume: {}